stages:
  get_raw_data:
    cmd: python -m src.data.scripts.get_raw_data
    deps:
      - src/data/scripts/get_raw_data.py
    outs:
      - data/raw

  train_model:
    cmd: python src/modeling/train.py
    deps:
      - data/raw
      - src/modeling/train.py
    outs:
      - models/bart-large-cnn-finetuned

  evaluate_model:
    cmd: PYTHONPATH=. pytest tests/test_model.py -v --junitxml=results/eval.xml
    deps:
      - models/bart-large-cnn-finetuned
      - data/raw
      - tests/test_model.py
      - src/modeling/predict.py
    metrics:
      - results/eval.xml
