stages:
  get_raw_data:
    cmd: python -m src.data.scripts.get_raw_data
    deps:
    - src/data/scripts/get_raw_data.py
    outs:
    - data/raw
  
  train_model:
    cmd: python -m src.modeling.train
    deps:
    - src/modeling/train.py
    - data/raw
    params:
    - model_name
    - task
    - max_length
    - min_length
    outs:
    - models/bart_summarizer
